export const allTimezones = [
  { "name": "Pago Pago", "offset": "(GMT-11:00)" },
  { "name": "Hawaii Time", "offset": "(GMT-10:00)" },
  { "name": "Pacific Time", "offset": "(GMT-08:00)" },
  { "name": "Pacific Time - Tijuana", "offset": "(GMT-08:00)" },
  { "name": "Mountain Time", "offset": "(GMT-07:00)" },
  { "name": "Mountain Time - Arizona", "offset": "(GMT-07:00)" },
  { "name": "Mountain Time - Chihuahua, Mazatlan", "offset": "(GMT-07:00)" },
  { "name": "Central Time", "offset": "(GMT-06:00)" },
  { "name": "Central Time - Mexico City", "offset": "(GMT-06:00)" },
  { "name": "Central Time - Regina", "offset": "(GMT-06:00)" },
  { "name": "Guatemala", "offset": "(GMT-06:00)" },
  { "name": "Bogota", "offset": "(GMT-05:00)" },
  { "name": "Eastern Time", "offset": "(GMT-05:00)" },
  { "name": "Lima", "offset": "(GMT-05:00)" },
  { "name": "Atlantic Time - Halifax", "offset": "(GMT-04:00)" },
  { "name": "Guyana", "offset": "(GMT-04:00)" },
  { "name": "La Paz", "offset": "(GMT-04:00)" },
  { "name": "Buenos Aires", "offset": "(GMT-03:00)" },
  { "name": "Godthab", "offset": "(GMT-03:00)" },
  { "name": "Montevideo", "offset": "(GMT-03:00)" },
  { "name": "Santiago", "offset": "(GMT-03:00)" },
  { "name": "Sao Paulo", "offset": "(GMT-02:00)" },
  { "name": "South Georgia", "offset": "(GMT-02:00)" },
  { "name": "Azores", "offset": "(GMT-01:00)" },
  { "name": "Cape Verde", "offset": "(GMT-01:00)" },
  { "name": "Casablanca", "offset": "(GMT+00:00)" },
  { "name": "Dublin", "offset": "(GMT+00:00)" },
  { "name": "Lisbon", "offset": "(GMT+00:00)" },
  { "name": "London", "offset": "(GMT+01:00)" },
  { "name": "Monrovia", "offset": "(GMT+00:00)" },
  { "name": "Algiers", "offset": "(GMT+01:00)" },
  { "name": "Amsterdam", "offset": "(GMT+01:00)" },
  { "name": "Berlin", "offset": "(GMT+01:00)" },
  { "name": "Brussels", "offset": "(GMT+01:00)" },
  { "name": "Budapest", "offset": "(GMT+01:00)" },
  { "name": "Central European Time - Belgrade", "offset": "(GMT+01:00)" },
  { "name": "Central European Time - Prague", "offset": "(GMT+01:00)" },
  { "name": "Copenhagen", "offset": "(GMT+01:00)" },
  { "name": "Madrid", "offset": "(GMT+01:00)" },
  { "name": "Paris", "offset": "(GMT+01:00)" },
  { "name": "Rome", "offset": "(GMT+01:00)" },
  { "name": "Stockholm", "offset": "(GMT+01:00)" },
  { "name": "Vienna", "offset": "(GMT+01:00)" },
  { "name": "Warsaw", "offset": "(GMT+01:00)" },
  { "name": "Athens", "offset": "(GMT+02:00)" },
  { "name": "Bucharest", "offset": "(GMT+02:00)" },
  { "name": "Cairo", "offset": "(GMT+02:00)" },
  { "name": "Jerusalem", "offset": "(GMT+02:00)" },
  { "name": "Johannesburg", "offset": "(GMT+02:00)" },
  { "name": "Helsinki", "offset": "(GMT+02:00)" },
  { "name": "Kiev", "offset": "(GMT+02:00)" },
  { "name": "Moscow-01 - Kaliningrad", "offset": "(GMT+02:00)" },
  { "name": "Riga", "offset": "(GMT+02:00)" },
  { "name": "Sofia", "offset": "(GMT+02:00)" },
  { "name": "Tallinn", "offset": "(GMT+02:00)" },
  { "name": "Vilnius", "offset": "(GMT+02:00)" },
  { "name": "Istanbul", "offset": "(GMT+03:00)" },
  { "name": "Baghdad", "offset": "(GMT+03:00)" },
  { "name": "Nairobi", "offset": "(GMT+03:00)" },
  { "name": "Minsk", "offset": "(GMT+03:00)" },
  { "name": "Riyadh", "offset": "(GMT+03:00)" },
  { "name": "Moscow+00 - Moscow", "offset": "(GMT+03:00)" },
  { "name": "Baku", "offset": "(GMT+04:00)" },
  { "name": "Moscow+01 - Samara", "offset": "(GMT+04:00)" },
  { "name": "Tbilisi", "offset": "(GMT+04:00)" },
  { "name": "Yerevan", "offset": "(GMT+04:00)" },
  { "name": "Karachi", "offset": "(GMT+05:00)" },
  { "name": "Moscow+02 - Yekaterinburg", "offset": "(GMT+05:00)" },
  { "name": "Tashkent", "offset": "(GMT+05:00)" },
  { "name": "Almaty", "offset": "(GMT+06:00)" },
  { "name": "Dhaka", "offset": "(GMT+06:00)" },
  { "name": "Bangkok", "offset": "(GMT+07:00)" },
  { "name": "Jakarta", "offset": "(GMT+07:00)" },
  { "name": "Moscow+04 - Krasnoyarsk", "offset": "(GMT+07:00)" },
  { "name": "China Time - Beijing", "offset": "(GMT+08:00)" },
  { "name": "Hong Kong", "offset": "(GMT+08:00)" },
  { "name": "Kuala Lumpur", "offset": "(GMT+08:00)" },
  { "name": "Moscow+05 - Irkutsk", "offset": "(GMT+08:00)" },
  { "name": "Singapore", "offset": "(GMT+08:00)" },
  { "name": "Taipei", "offset": "(GMT+08:00)" },
  { "name": "Ulaanbaatar", "offset": "(GMT+08:00)" },
  { "name": "Western Time - Perth", "offset": "(GMT+08:00)" },
  { "name": "Moscow+06 - Yakutsk", "offset": "(GMT+09:00)" },
  { "name": "Seoul", "offset": "(GMT+09:00)" },
  { "name": "Tokyo", "offset": "(GMT+09:00)" },
  { "name": "Eastern Time - Brisbane", "offset": "(GMT+10:00)" },
  { "name": "Guam", "offset": "(GMT+10:00)" },
  { "name": "Moscow+07 - Magadan", "offset": "(GMT+10:00)" },
  { "name": "Moscow+07 - Yuzhno-Sakhalinsk", "offset": "(GMT+10:00)" },
  { "name": "Port Moresby", "offset": "(GMT+10:00)" },
  { "name": "Eastern Time - Hobart", "offset": "(GMT+11:00)" },
  { "name": "Eastern Time - Melbourne, Sydney", "offset": "(GMT+11:00)" },
  { "name": "Guadalcanal", "offset": "(GMT+11:00)" },
  { "name": "Noumea", "offset": "(GMT+11:00)" },
  { "name": "Majuro", "offset": "(GMT+12:00)" },
  { "name": "Moscow+09 - Petropavlovsk-Kamchatskiy", "offset": "(GMT+12:00)" },
  { "name": "Auckland", "offset": "(GMT+13:00)" },
  { "name": "Fakaofo", "offset": "(GMT+13:00)" },
  { "name": "Fiji", "offset": "(GMT+13:00)" },
  { "name": "Tongatapu", "offset": "(GMT+13:00)" },
  { "name": "Asia", "offset": "(GMT+14:00)" }
]

  